"""initial migration

Revision ID: 59378b41d041
Revises:
Create Date: 2026-05-01 11:20:51.219440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59378b41d041'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=True),
    sa.Column('profile_image', sa.String(length=255), nullable=False),
    sa.Column('profile_background', sa.String(length=20), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('favorite_character', sa.String(length=20), nullable=False),
    sa.Column('show_stats_to_friends', sa.Boolean(), nullable=False),
    sa.Column('allow_friend_messages', sa.Boolean(), nullable=False),
    sa.Column('hide_from_leaderboard', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('chat_public_key', sa.Text(), nullable=True),
    sa.Column('chat_key_id', sa.String(length=64), nullable=True),
    sa.Column('chat_key_created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('friend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friend_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('ciphertext', sa.Text(), nullable=True),
    sa.Column('nonce', sa.String(length=64), nullable=True),
    sa.Column('sender_key_id', sa.String(length=64), nullable=True),
    sa.Column('sender_public_key', sa.Text(), nullable=True),
    sa.Column('recipient_key_id', sa.String(length=64), nullable=True),
    sa.Column('recipient_public_key', sa.Text(), nullable=True),
    sa.Column('encryption_version', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_user_id', sa.Integer(), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['profile_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_reaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_user_id', sa.Integer(), nullable=False),
    sa.Column('reactor_user_id', sa.Integer(), nullable=False),
    sa.Column('reaction_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reactor_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_user_id', 'reactor_user_id', name='uq_profile_reaction')
    )
    op.create_table('save_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('character_id', sa.String(length=20), nullable=False),
    sa.Column('health', sa.Integer(), nullable=False),
    sa.Column('medkits', sa.Integer(), nullable=False),
    sa.Column('grenades', sa.Integer(), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('damage_dealt', sa.Integer(), nullable=False),
    sa.Column('damage_taken', sa.Integer(), nullable=False),
    sa.Column('pistol_shots', sa.Integer(), nullable=False),
    sa.Column('grenades_used', sa.Integer(), nullable=False),
    sa.Column('medkits_used', sa.Integer(), nullable=False),
    sa.Column('reloads', sa.Integer(), nullable=False),
    sa.Column('knife_uses', sa.Integer(), nullable=False),
    sa.Column('ammo_in_gun', sa.Integer(), nullable=False),
    sa.Column('ammo_in_bag', sa.Integer(), nullable=False),
    sa.Column('mag_capacity', sa.Integer(), nullable=False),
    sa.Column('laser_upgrade', sa.Boolean(), nullable=False),
    sa.Column('shield_owned', sa.Boolean(), nullable=False),
    sa.Column('shield_on', sa.Boolean(), nullable=False),
    sa.Column('current_level_id', sa.String(length=20), nullable=False),
    sa.Column('enemies_remaining', sa.Integer(), nullable=False),
    sa.Column('level_complete', sa.Boolean(), nullable=False),
    sa.Column('awaiting_choice', sa.Boolean(), nullable=False),
    sa.Column('game_won', sa.Boolean(), nullable=False),
    sa.Column('has_started_game', sa.Boolean(), nullable=False),
    sa.Column('run_state_json', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_achievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.String(length=80), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_user_achievement')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_achievement')
    op.drop_table('save_data')
    op.drop_table('profile_reaction')
    op.drop_table('profile_comment')
    op.drop_table('message')
    op.drop_table('friend_request')
    op.drop_table('friend')
    op.drop_table('user')
    # ### end Alembic commands ###
